about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.description, name='description'),
]

anfisa_for_friends/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('about/', include('about.urls', namespace='about')),
    path('ice_cream/', include('ice_cream.urls', namespace='ice_cream')),
    path('admin/', admin.site.urls),
]

homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

ice_cream/urls.py
from django.urls import path

from . import views

app_name = 'ice_cream'

urlpatterns = [
    path('', views.ice_cream_list, name='ice_cream_list'),
    path('<int:pk>/', views.ice_cream_detail, name='ice_cream_detail'),
]

about/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

ice_cream/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render


def description(request):
    template = 'about/description.html'
    return render(request, template)

homepage/views.py
from django.shortcuts import render


def index(request):
    template = 'homepage/index.html'
    return render(request, template)

ice_cream/views.py
from django.shortcuts import render

ice_cream_catalog = [
    {
        'id': 0,
        'title': 'Классический пломбир',
        'description': 'Настоящее мороженое, для истинных ценителей вкуса. '
                       'Если на столе появляется пломбир — это не надолго.',
    },
    {
        'id': 1,
        'title': 'Мороженое с кузнечиками',
        'description': 'В колумбийском стиле: мороженое '
                       'с добавлением настоящих карамелизованных кузнечиков.',
    },
    {
        'id': 2,
        'title': 'Мороженое со вкусом сыра чеддер',
        'description': 'Вкус настоящего сыра в вафельном стаканчике.',
    },
]


def ice_cream_detail(request, pk):
    template = 'ice_cream/detail.html'
    context = {'ice_cream': ice_cream_catalog[pk]}
    return render(request, template, context)


def ice_cream_list(request):
    template = 'ice_cream/list.html'
    context = {'ice_cream_list': ice_cream_catalog}
    return render(request, template, context)

templates/about/description.html
{% extends "base.html" %}
{% block title %}
  Анфиса для друзей. О проекте
{% endblock %}
{% block content %}
  {% comment %} <h1>Описание проекта</h1> {% endcomment %}
  <!-- Блок content -->
  <h1 class="pb-2 mb-0">О проекте</h1>
  <p>
    Каталог экзотических сортов мороженого.
  </p>
  <!-- Конец блока content -->
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include "includes/header.html" %}
    {% comment %} <main>
      {% block content %}
      {% endblock %}
    </main> {% endcomment %}
    <main class="pt-5 my-5">       
      <div class="container">
        {% block content %}Пусто
        {% endblock %}     
      </div> 
    </main>
    {% include "includes/footer.html" %}   
  </body>
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>

templates/homepage/index.html
{% extends "base.html" %}
{% block title %}
  Анфиса для друзей. Главная
{% endblock %}
{% block content %}
  <h1 class="pb-2 mb-0">Главная страница</h1>
{% endblock %}

templates/ice_cream/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Анфиса для друзей. Подробное описание мороженого
{% endblock %}

{% block content %}
<!-- Блок content -->
<h1 class="pb-2 mb-0">{{ ice_cream.title }}</h1>  
<div class="row mt-3">
  <div class="col-12 col-md-6">
    <h2>Описание</h2>
    <p>{{ ice_cream.description }}</p>      
  </div> 
  <div class="col-12 col-md-6 mb-3">
    <!-- Картинку берём из статики -->
    <img 
      class="img-fluid" 
      height="400" width="300"
      src="{% static 'img/image-holder.png' %}"
      >      
  </div>
</div>     
<!-- Конец блока content --> 
{% endblock %}

templates/ice_cream/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Анфиса для друзей. Каталог мороженого
{% endblock %}
{% block content %}
<h1 class="pb-2 mb-0">Каталог мороженого</h1>
  <div class="row">
  <!-- Начинается перебор мороженого  в цикле -->
  {% for ice_cream in ice_cream_list %}
      <!-- Карточка товара 0 -->
      <div class="col-6 col-md-4 my-1">
        <div class="card">
          <!-- Картинку берём из статики -->
          <img 
            class="img-fluid card-img-top" 
            height="400" width="300"
            src="{% static 'img/image-holder.png' %}"
          >
          <div class="card-body">           
            <h5 class="card-title">{{ice_cream.title}}</h5>
            <p class="card-text">
              <!-- Описание обрезано до первых 10ти слов -->
              {{ ice_cream.description|truncatewords:10 }}
            </p>
            <!-- Ссылка на товар 0 -->
            <a class="mt-3 regular-link" href="{% url 'ice_cream:ice_cream_detail' ice_cream.id %}">
              Подробнее -->           
            </a>
          </div>
        </div>
      </div>
    {% endfor %}
      <!-- Конец карточки товара 0 -->
      {% comment %} <!-- Карточка товара 1 -->
      <div class="col-6 col-md-4 my-1">
        <div class="card">                  
          <img 
            class="img-fluid card-img-top" 
            height="400" width="300"
            src="img/image-holder.png"
          >
          <div class="card-body">           
            <h5 class="card-title">Мороженое с кузнечиками</h5>
            <p class="card-text">
              <!-- Описание обрезано до первых 10ти слов -->
              В колумбийском стиле: мороженое с добавлением настоящих карамелизованных кузнечиков.
            </p>
            <!-- Ссылка на товар 1 -->
            <a class="mt-3 regular-link" href="ice_cream_detail.html">
              Подробнее -->           
            </a>
          </div>
        </div>
      </div>
      <!-- Конец карточки товара 1 -->
      <!-- Карточка товара 2 -->
      <div class="col-6 col-md-4 my-1">
        <div class="card">                  
          <img 
            class="img-fluid card-img-top" 
            height="400" width="300"
            src="img/image-holder.png"
          >
          <div class="card-body">           
            <h5 class="card-title">Мороженое со вкусом сыра чеддер</h5>
            <p class="card-text">
              <!-- Описание обрезано до первых 10ти слов -->
              Вкус настоящего сыра в вафельном стаканчике.
            </p>
            <!-- Ссылка на товар 2 -->
            <a class="mt-3 regular-link" href="ice_cream_detail.html">
              Подробнее -->           
            </a>
          </div>
        </div>
      </div>
      <!-- Конец карточки товара 2 -->
    <!-- Конец цикла  -->
  </div> {% endcomment %}
<!-- Конец блока content --> 
{% endblock %}

templates/includes/footer.html
{% comment %} <footer>
  <p>Копирайт, год создания</p>
</footer>  {% endcomment %}

<!-- Вынести в footer.html -->
<footer class="border-top text-center py-3">
  <p>© 2022 «MyKit Corp»</p>
</footer>
<!-- Конец footer.html -->  

templates/includes/header.html
{% comment %} {% load static %}
<header>
  <img src="{% static 'img/logo.png' %}" height="50" alt="">
  <nav>
    <ul>
      <li>
        <a href="{% url 'homepage:index' %}">Главная</a>  
      </li>
      <li>
        <a href="{% url 'ice_cream:ice_cream_list' %}">Каталог мороженого</a>       
      </li>
      <li>
        <a href="{% url 'about:description' %}">О проекте</a>
      </li>
    </ul>
  </nav>
</header> {% endcomment %}

<!-- Вынести в header.html -->
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow-sm">
    <div class="container">
      <div 
        class="navbar-toggler" 
        type="button" 
        data-toggle="collapse" 
        data-target="#navbarNav" 
        aria-controls="navbarNav" 
        aria-expanded="false" 
        aria-label="Toggle navigation"
        >
        <span class="navbar-toggler-icon"></span>
      </div>
      <div class="collapse navbar-collapse" id="navbarNav">                      
        <ul class="nav nav-pills">
          <li class="nav-item">
            <!-- Добавлен класс active -->              
            <a class="nav-link
              {% if view_name == 'homepage:index' %}
                active
              {% endif %}"
              href="{% url 'homepage:index' %}">
              Главная
            </a> 
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name == 'ice_cream:ice_cream_list' %}
                active
              {% endif %}"
              href="{% url 'ice_cream:ice_cream_list' %}">
              Каталог мороженого
            </a> 
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name == 'about:description' %}
                active
              {% endif %}"            
              href="{% url 'about:description' %}">
              О проекте
            </a> 
          </li>
        </ul>
      </div> 
      <a class="navbar-brand" href="{% url 'homepage:index' %}">
        <img src="{% static 'img/logo.png' %}" height="50" class="d-inline-block align-top" alt="">            
      </a>         
    </div>
  </nav>
</header>
{% endwith %}
<!-- Конец header.html -->